spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petservices?useSLL=false&serverTimezone=UTC  # Database URL
    username: root  # Database username
    password: huythang02  # Database password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver class name
  jpa:
    hibernate:
      ddl-auto: none  # Hibernate schema auto-update strategy
    show-sql: true  # Show SQL queries in console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Hibernate dialect for MySQL 8
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 2592000 # in second
  refreshable-duration: 36000 # in seconds

api:
  prefix: api/v1

cloudinary:
  cloud-name: dsoz9gcfd
  api-key: 791357523784923
  api-secret: NgevDFEbDQCBM08mo5lsvW93l40

outbound:
  identity:
    client-id: "296253261995-l9h9uurvmsmb31l9lenrv3iau6p1c6lj.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:3000"

google:
  api:
    key: "AIzaSyCRU8BG96rtvdlTRv4j78TY__97su54kzc"

vnp:
  partnerCode: K126GZDF
  accessKey: ACCESS_KEY
  secretKey: AVUIGDB260WKO4IV9VJMDZGUDOZLHUQU
  endpoint: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html